# Base
title:          Bash Fu - Styleguide
tagline:        An opinionated bash scripting styleguide crafted over 20 years
description:    An opinionated bash scripting styleguide crafted over 20 years
url:            https://style.bashfu.com/
#theme:          jekyll-theme-minimal
remote_theme:   krayon/jekyll-theme-tactile

# Theme specifics: Tactile
show_downloads: false

# Author
author:
  name:         Krayon
  url:          https://krayon.me/

# Gems
plugins:
  - jekyll-remote-theme

# Custom vars
#version:     1.1.0
