# This workflow will build Table of Contents (TOC) for markdown files and
# commit them to the `gh-pages` branch.

name: build-toc

on:
  # Allow manual running
  workflow_dispatch:

  # Automatically run this workflow on commit to `main` branch
  push:
    branches:
      - main
      - testing

jobs:
  build-toc:
    runs-on: ubuntu-latest

    env:
      ref: ${{ github.ref }}

    steps:
      # Checkout the code base
      - name: Checkout "${ref}" branch
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: check stuff
        run: |
          echo 'git branch -avv'
          git branch -avv
          echo 'git remote -vv'
          git remote -vv
          echo 'git log'
          git log
          echo '--------------------'
          git fetch origin gh-pages
          echo 'git log gh-pages'
          git log origin/gh-pages
          sleep 1

      # Prepare the branch
      - name: Preparing gh-pages branch
        run: |
          git fetch origin gh-pages
          echo "git checkout -b gh-pages origin/gh-pages || git checkout -b gh-pages \"${ref}\""
          git checkout -b gh-pages origin/gh-pages || git checkout -b gh-pages "${ref}"
          echo 'git log gh-pages'
          git log gh-pages
          echo "git log \"${ref}\""
          git log "${ref}"
          echo "git merge -m 'Auto-generate TOC' \"${ref}\""
          git merge -m 'Auto-generate TOC' "${ref}"

      # Retrieve fast markdown TOC generator
      - name: Download fast markdown TOC generator
        run: |
          wget -q https://raw.githubusercontent.com/krayon/qdnxtools/refs/heads/main/markdown-toc-creator.bash
          chmod +x markdown-toc-creator.bash

      # Generate the TOCs
      - name: Generate TOCs
        run: |
          cp -a "README.md" "README.src"
          ./markdown-toc-creator.bash <"README.src" >"README.md"
          rm README.src

      # Commit changes
      - name: Commit changed files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -u
          git diff --cached --quiet || git commit -m "Auto-generate TOC"
          git push origin gh-pages:gh-pages
